### ISSUE TITLE
Can you provide examples for all the functions

### ISSUE THREAD

**Issue by joethorley** [nhejazi/txshift#59]
> Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

**Comment by joethorley** [comment]
https://github.com/openjournals/joss-reviews/issues/2447

**Comment by nhejazi** [comment]
Thanks for raising this point. This package isn't intended to expose many user-facing functions - primarily, these are just `txshift()` and `msm_vimshift()`, alongside any methods exposed for the S3 classes these introduce (e.g., `summary`, `plot`). Following CRAN guidelines, we've provided examples for each of these functions and methods; however, there are a number of internal functions that are not intended to be user-facing.

We hope that this alleviates some of the concern around functions without examples in their documentation but would be happy to discuss any lingering concerns further.

**Comment by joethorley** [comment]
@nhejazi - I saw the detailed documentation on various internal functions and assumed they were exported. You are quite right and I am closing this issue.
