### ISSUE TITLE
delta specification issue

### ISSUE THREAD

**Issue by alexpkeil1** [nhejazi/txshift#65]
I'm using the version of txshift currently up on CRAN. My understanding of what this package is doing may be flawed, but I think the specification of delta is broken somewhere. If specifying delta = 0, for continuous treatment (A) I intuit this means we are estimating E_n(E(Y | A=a+0, W=w)) - E_n(E(Y | A=a, W=w)) = 0. This does not seem to be what the package is estimating - see example below (based on example in package documentation).

```
n_obs <- 1000  # number of observations
n_w <- 1  # number of baseline covariates
tx_mult <- 2  # multiplier for the effect of W = 1 on the treatment
W <- as.numeric(replicate(n_w, rbinom(n_obs, 1, 0.5)))
A <- as.numeric(rnorm(n_obs, mean = tx_mult * W, sd = 1))
Y <- A + W + rnorm(n_obs, mean = 0, sd = 1)


tmle_hal_shift_1 <- txshift(
  W = W, A = A, Y = Y, delta = 0.0,
  fluctuation = "standard",
  g_exp_fit_args = list(fit_type = "hal", n_bins = 5,
                        grid_type = "equal_mass",
                        lambda_seq = exp(seq(-1, -12, length = 500))),
  Q_fit_args = list(fit_type = "glm", glm_formula = "Y ~ .")
)
tmle_hal_shift_1

```

Counterfactual Mean of Shifted Treatment
    Intervention: Treatment + 0

txshift Estimator: tmle
    Estimate: 1.537
    Std. Error: 0.0663
    95% CI: [1.407, 1.6671]

**Comment by benkeser** [comment]
I think the function returns estimates of E(E(Y | A + delta, W)). @nhejazi will know better though — I’m just the clueless advisor here.

**Comment by alexpkeil1** [comment]
Awwww geez. I was following along with the wrong Diaz and van der Laan paper. Thanks!

**Comment by nhejazi** [comment]
Thanks for bringing this up @alexpkeil1, but @benkeser is right: the `txshift()` function return an estimate of the parameter EY_{A+delta}, which is only one half of the population intervention effect (PIE) that Diaz+vdL write about, i.e., theta_{PIE} = EY - EY_{A+delta}. If your goal is to estimate instead the PIE, this can be done with just what's returned by the `txshift()` function (by applying the delta method).

**Comment by alexpkeil1** [comment]
Thanks so much! Sorry for my confusion.
